Sprint 1
req-dev/middle.messenger.praktikum.yandex pull request #5
Opened 2024-12-06 18:02 UTC by req-dev

2024-12-06 21:47 UTC, aromanovnik requested changes
Добрый день, Dima!

Работа выполнена очень хорошо: проект успешно задеплоен на Netlify, уникальный дизайн, запуск команды `npm audit` выявил **0** уязвимостей, главный контент страницы обернут в тег `<main>`, используется TypeScript и типизация, все атрибуты `name` соответствуют требованиям. Код выглядит чисто и структурированно.

Тем не менее, есть несколько замечаний, которые потребуют доработки. Более подробно о них написано в комментариях к коду.

Что нужно исправить:
* Теги `<label>` следует связывать с элементом управления для улучшения доступности. Это можно сделать двумя способами: поместить элемент управления внутрь `<label>`, либо использовать атрибут `for`. Чтобы избежать необходимости синхронизировать идентификаторы между input и label, удобнее обернуть input внутри тега label: `<label>Текст<input name="login"></label>`. Более подробно можно почитать  https://developer.mozilla.org/ru/docs/Web/HTML/Element/label
* Согласно заданию, для перехода между страницами необходимо использовать ссылки. Следует создать простой список с ссылками на все страницы.
* Заголовки на странице должны быть обёрнуты в соответствующие теги уровней `h1…h6`. Это помогает соблюсти правильную иерархию заголовков, улучшает доступность для экранных читалок и оптимизирует SEO.

Что можно улучшить:
* Поскольку интерфейс проекта русскоязычный, рекомендуется установить атрибут языка в корневом теге `<html lang="ru">`. Это предотвратит ситуации, когда устройства или браузеры могут неправильно определять язык страницы, предлагать перевод, либо автоматически изменять содержимое. Подробнее об одной из таких проблем: https://habr.com/ru/post/650907/
* Все цвета лучше вынести в CSS-переменные, чтобы улучшить поддержку кода. Это позволяет мгновенно понять назначение цвета, избежать дублирования, а также облегчить изменения — достаточно подкорректировать цвет в одном месте, что повышает гибкость и масштабируемость стилей.
* Каждой картинке (тегу `img`) следует добавить информативный атрибут `alt` (**Не пустой**). Это важно не только для улучшения доступности сайта, но и для SEO. В случае ошибки загрузки изображения, в `alt` будет отображаться описание, и пользователи смогут понять, что изображение не удалось загрузить. Атрибут alt также необходим для пользователей с нарушениями зрения, так как специальные программы для чтения с экрана могут озвучивать текст в alt. Для дополнительной информации можно ознакомиться: https://habr.com/ru/articles/341810/

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-12-06 21:47 UTC, aromanovnik commented on index.html
> +<html lang="en">
**Можно лучше**: Поскольку интерфейс проекта русскоязычный, рекомендуется установить атрибут языка в корневом теге `<html lang="ru">`. Это предотвратит ситуации, когда устройства или браузеры могут неправильно определять язык страницы, предлагать перевод, либо автоматически изменять содержимое. Подробнее об одной из таких проблем: https://habr.com/ru/post/650907/

2024-12-06 21:47 UTC, aromanovnik commented on src/components/Input/index.ts
> +    <label class="input__hint">{{hint}}</label>
**Надо исправить**: Теги `<label>` следует связывать с элементом управления для улучшения доступности. Это можно сделать двумя способами: поместить элемент управления внутрь `<label>`, либо использовать атрибут `for`. Чтобы избежать необходимости синхронизировать идентификаторы между input и label, удобнее обернуть input внутри тега label: `<label>Текст<input name="login"></label>`. Более подробно можно почитать  https://developer.mozilla.org/ru/docs/Web/HTML/Element/label

2024-12-06 21:47 UTC, aromanovnik commented on src/App.tsx
> +            currentPage:'login'
**Надо исправить**: Согласно заданию, для перехода между страницами необходимо использовать ссылки. Следует создать простой список с ссылками на все страницы.

<img width="640" alt="Снимок экрана 2024-12-07 в 00 20 24" src="https://github.com/user-attachments/assets/501b41fa-25aa-4b6f-873e-87a244877c40">

2024-12-06 21:47 UTC, aromanovnik commented on src/pages/error/template.hbs
> +        <div class="error-page__code">{{code}}</div>
**Надо исправить**: Заголовки на странице должны быть обёрнуты в соответствующие теги уровней h1…h6. Это помогает соблюсти правильную иерархию заголовков, улучшает доступность для экранных читалок и оптимизирует SEO.

2024-12-06 21:47 UTC, aromanovnik commented on src/components/ChatItem/style.pcss
> +    color: #fff;
**Можно лучше**: Все цвета лучше вынести в CSS-переменные, чтобы улучшить поддержку кода. Это позволяет мгновенно понять назначение цвета, избежать дублирования, а также облегчить изменения — достаточно подкорректировать цвет в одном месте, что повышает гибкость и масштабируемость стилей.

2024-12-06 21:47 UTC, aromanovnik commented on src/components/ChatItem/index.ts
> +    <img src="{{src}}" class="chat-item__img" alt="">
**Можно лучше**: Каждой картинке (тегу `img`) следует добавить информативный атрибут `alt` (**Не пустой**). Это важно не только для улучшения доступности сайта, но и для SEO. В случае ошибки загрузки изображения, в `alt` будет отображаться описание, и пользователи смогут понять, что изображение не удалось загрузить. Атрибут alt также необходим для пользователей с нарушениями зрения, так как специальные программы для чтения с экрана могут озвучивать текст в alt. Для дополнительной информации можно ознакомиться: https://habr.com/ru/articles/341810/

2024-12-07 04:45 UTC, req-dev commented on index.html
> +<html lang="en">
Добрый день, интерфейс проекта как раз на английском

2024-12-07 04:46 UTC, req-dev commented on src/App.tsx
> +            currentPage:'login'
Я добавил в Readme файл ссылки на все страницы

2024-12-07 06:04 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. Желаю успехов в дальнейшей учебе!

2024-12-11 05:41 UTC, merged